# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T9.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1204, 739)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rotating_90 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_90.setGeometry(QtCore.QRect(20, 40, 41, 41))
        self.rotating_90.setObjectName("rotating_90")
        self.rotating_180 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_180.setGeometry(QtCore.QRect(80, 40, 41, 41))
        self.rotating_180.setObjectName("rotating_180")
        self.rotating_270 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_270.setGeometry(QtCore.QRect(140, 40, 41, 41))
        self.rotating_270.setObjectName("rotating_270")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(30, 90, 151, 151))
        self.label_1.setAutoFillBackground(False)
        self.label_1.setObjectName("label_1")
        self.xiayiye = QtWidgets.QPushButton(self.centralwidget)
        self.xiayiye.setGeometry(QtCore.QRect(910, 10, 75, 23))
        self.xiayiye.setObjectName("xiayiye")
        self.shangyiye = QtWidgets.QPushButton(self.centralwidget)
        self.shangyiye.setGeometry(QtCore.QRect(770, 10, 75, 23))
        self.shangyiye.setObjectName("shangyiye")
        self.open = QtWidgets.QPushButton(self.centralwidget)
        self.open.setGeometry(QtCore.QRect(240, 10, 75, 23))
        self.open.setObjectName("open")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 211, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.rotating_270_2 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_270_2.setGeometry(QtCore.QRect(340, 40, 41, 41))
        self.rotating_270_2.setObjectName("rotating_270_2")
        self.rotating_180_2 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_180_2.setGeometry(QtCore.QRect(280, 40, 41, 41))
        self.rotating_180_2.setObjectName("rotating_180_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 90, 151, 151))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setObjectName("label_2")
        self.rotating_90_2 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_90_2.setGeometry(QtCore.QRect(220, 40, 41, 41))
        self.rotating_90_2.setObjectName("rotating_90_2")
        self.rotating_270_3 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_270_3.setGeometry(QtCore.QRect(530, 40, 41, 41))
        self.rotating_270_3.setObjectName("rotating_270_3")
        self.rotating_18_3 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_18_3.setGeometry(QtCore.QRect(470, 40, 41, 41))
        self.rotating_18_3.setObjectName("rotating_18_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(420, 90, 151, 151))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setObjectName("label_3")
        self.rotating_90_3 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_90_3.setGeometry(QtCore.QRect(410, 40, 41, 41))
        self.rotating_90_3.setObjectName("rotating_90_3")
        self.rotating_273 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_273.setGeometry(QtCore.QRect(740, 40, 41, 41))
        self.rotating_273.setObjectName("rotating_273")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(630, 90, 151, 151))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setObjectName("label_4")
        self.rotating_93 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_93.setGeometry(QtCore.QRect(620, 40, 41, 41))
        self.rotating_93.setObjectName("rotating_93")
        self.rotating_183 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_183.setGeometry(QtCore.QRect(680, 40, 41, 41))
        self.rotating_183.setObjectName("rotating_183")
        self.rotating_274 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_274.setGeometry(QtCore.QRect(930, 40, 41, 41))
        self.rotating_274.setObjectName("rotating_274")
        self.rotating_184 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_184.setGeometry(QtCore.QRect(870, 40, 41, 41))
        self.rotating_184.setObjectName("rotating_184")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(820, 90, 151, 151))
        self.label_5.setAutoFillBackground(False)
        self.label_5.setObjectName("label_5")
        self.rotating_94 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_94.setGeometry(QtCore.QRect(810, 40, 41, 41))
        self.rotating_94.setObjectName("rotating_94")
        self.rotating_275 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_275.setGeometry(QtCore.QRect(1130, 40, 41, 41))
        self.rotating_275.setObjectName("rotating_275")
        self.rotating_95 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_95.setGeometry(QtCore.QRect(1010, 40, 41, 41))
        self.rotating_95.setObjectName("rotating_95")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(1020, 90, 151, 151))
        self.label_6.setAutoFillBackground(False)
        self.label_6.setObjectName("label_6")
        self.rotating_185 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_185.setGeometry(QtCore.QRect(1070, 40, 41, 41))
        self.rotating_185.setObjectName("rotating_185")
        self.rotating_186 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_186.setGeometry(QtCore.QRect(1070, 260, 41, 41))
        self.rotating_186.setObjectName("rotating_186")
        self.rotating_276 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_276.setGeometry(QtCore.QRect(340, 260, 41, 41))
        self.rotating_276.setObjectName("rotating_276")
        self.rotating_187 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_187.setGeometry(QtCore.QRect(470, 260, 41, 41))
        self.rotating_187.setObjectName("rotating_187")
        self.rotating_188 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_188.setGeometry(QtCore.QRect(80, 260, 41, 41))
        self.rotating_188.setObjectName("rotating_188")
        self.rotating_277 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_277.setGeometry(QtCore.QRect(930, 260, 41, 41))
        self.rotating_277.setObjectName("rotating_277")
        self.rotating_96 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_96.setGeometry(QtCore.QRect(20, 260, 41, 41))
        self.rotating_96.setObjectName("rotating_96")
        self.rotating_278 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_278.setGeometry(QtCore.QRect(140, 260, 41, 41))
        self.rotating_278.setObjectName("rotating_278")
        self.rotating_97 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_97.setGeometry(QtCore.QRect(1010, 260, 41, 41))
        self.rotating_97.setObjectName("rotating_97")
        self.rotating_98 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_98.setGeometry(QtCore.QRect(620, 260, 41, 41))
        self.rotating_98.setObjectName("rotating_98")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(420, 310, 151, 151))
        self.label_9.setAutoFillBackground(False)
        self.label_9.setObjectName("label_9")
        self.rotating_189 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_189.setGeometry(QtCore.QRect(870, 260, 41, 41))
        self.rotating_189.setObjectName("rotating_189")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(820, 310, 151, 151))
        self.label_11.setAutoFillBackground(False)
        self.label_11.setObjectName("label_11")
        self.rotating_99 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_99.setGeometry(QtCore.QRect(220, 260, 41, 41))
        self.rotating_99.setObjectName("rotating_99")
        self.rotating_279 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_279.setGeometry(QtCore.QRect(740, 260, 41, 41))
        self.rotating_279.setObjectName("rotating_279")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 310, 151, 151))
        self.label_7.setAutoFillBackground(False)
        self.label_7.setObjectName("label_7")
        self.rotating_190 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_190.setGeometry(QtCore.QRect(280, 260, 41, 41))
        self.rotating_190.setObjectName("rotating_190")
        self.rotating_100 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_100.setGeometry(QtCore.QRect(810, 260, 41, 41))
        self.rotating_100.setObjectName("rotating_100")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(630, 310, 151, 151))
        self.label_10.setAutoFillBackground(False)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(1020, 310, 151, 151))
        self.label_12.setAutoFillBackground(False)
        self.label_12.setObjectName("label_12")
        self.rotating_280 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_280.setGeometry(QtCore.QRect(530, 260, 41, 41))
        self.rotating_280.setObjectName("rotating_280")
        self.rotating_281 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_281.setGeometry(QtCore.QRect(1130, 260, 41, 41))
        self.rotating_281.setObjectName("rotating_281")
        self.rotating_191 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_191.setGeometry(QtCore.QRect(680, 260, 41, 41))
        self.rotating_191.setObjectName("rotating_191")
        self.rotating_101 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_101.setGeometry(QtCore.QRect(410, 260, 41, 41))
        self.rotating_101.setObjectName("rotating_101")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(230, 310, 151, 151))
        self.label_8.setAutoFillBackground(False)
        self.label_8.setObjectName("label_8")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(230, 520, 151, 151))
        self.label_14.setAutoFillBackground(False)
        self.label_14.setObjectName("label_14")
        self.rotating_282 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_282.setGeometry(QtCore.QRect(740, 470, 41, 41))
        self.rotating_282.setObjectName("rotating_282")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(420, 520, 151, 151))
        self.label_15.setAutoFillBackground(False)
        self.label_15.setObjectName("label_15")
        self.rotating_192 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_192.setGeometry(QtCore.QRect(80, 470, 41, 41))
        self.rotating_192.setObjectName("rotating_192")
        self.rotating_102 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_102.setGeometry(QtCore.QRect(410, 470, 41, 41))
        self.rotating_102.setObjectName("rotating_102")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(1020, 520, 151, 151))
        self.label_18.setAutoFillBackground(False)
        self.label_18.setObjectName("label_18")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 520, 151, 151))
        self.label_13.setAutoFillBackground(False)
        self.label_13.setObjectName("label_13")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(820, 520, 151, 151))
        self.label_17.setAutoFillBackground(False)
        self.label_17.setObjectName("label_17")
        self.rotating_193 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_193.setGeometry(QtCore.QRect(680, 470, 41, 41))
        self.rotating_193.setObjectName("rotating_193")
        self.rotating_103 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_103.setGeometry(QtCore.QRect(220, 470, 41, 41))
        self.rotating_103.setObjectName("rotating_103")
        self.rotating_283 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_283.setGeometry(QtCore.QRect(340, 470, 41, 41))
        self.rotating_283.setObjectName("rotating_283")
        self.rotating_104 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_104.setGeometry(QtCore.QRect(810, 470, 41, 41))
        self.rotating_104.setObjectName("rotating_104")
        self.rotating_105 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_105.setGeometry(QtCore.QRect(20, 470, 41, 41))
        self.rotating_105.setObjectName("rotating_105")
        self.rotating_106 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_106.setGeometry(QtCore.QRect(1010, 470, 41, 41))
        self.rotating_106.setObjectName("rotating_106")
        self.rotating_284 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_284.setGeometry(QtCore.QRect(140, 470, 41, 41))
        self.rotating_284.setObjectName("rotating_284")
        self.rotating_194 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_194.setGeometry(QtCore.QRect(470, 470, 41, 41))
        self.rotating_194.setObjectName("rotating_194")
        self.rotating_195 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_195.setGeometry(QtCore.QRect(280, 470, 41, 41))
        self.rotating_195.setObjectName("rotating_195")
        self.rotating_196 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_196.setGeometry(QtCore.QRect(1070, 470, 41, 41))
        self.rotating_196.setObjectName("rotating_196")
        self.rotating_285 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_285.setGeometry(QtCore.QRect(930, 470, 41, 41))
        self.rotating_285.setObjectName("rotating_285")
        self.rotating_286 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_286.setGeometry(QtCore.QRect(530, 470, 41, 41))
        self.rotating_286.setObjectName("rotating_286")
        self.rotating_107 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_107.setGeometry(QtCore.QRect(620, 470, 41, 41))
        self.rotating_107.setObjectName("rotating_107")
        self.rotating_197 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_197.setGeometry(QtCore.QRect(870, 470, 41, 41))
        self.rotating_197.setObjectName("rotating_197")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(630, 520, 151, 151))
        self.label_16.setAutoFillBackground(False)
        self.label_16.setObjectName("label_16")
        self.rotating_287 = QtWidgets.QPushButton(self.centralwidget)
        self.rotating_287.setGeometry(QtCore.QRect(1130, 470, 41, 41))
        self.rotating_287.setObjectName("rotating_287")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1204, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rotating_90.setText(_translate("MainWindow", "90°"))
        self.rotating_180.setText(_translate("MainWindow", "180°"))
        self.rotating_270.setText(_translate("MainWindow", "270°"))
        self.label_1.setText(_translate("MainWindow", "图片1"))
        self.xiayiye.setText(_translate("MainWindow", "下一页"))
        self.shangyiye.setText(_translate("MainWindow", "上一页"))
        self.open.setText(_translate("MainWindow", "open"))
        self.rotating_270_2.setText(_translate("MainWindow", "270°"))
        self.rotating_180_2.setText(_translate("MainWindow", "180°"))
        self.label_2.setText(_translate("MainWindow", "图片1"))
        self.rotating_90_2.setText(_translate("MainWindow", "90°"))
        self.rotating_270_3.setText(_translate("MainWindow", "270°"))
        self.rotating_18_3.setText(_translate("MainWindow", "180°"))
        self.label_3.setText(_translate("MainWindow", "图片1"))
        self.rotating_90_3.setText(_translate("MainWindow", "90°"))
        self.rotating_273.setText(_translate("MainWindow", "270°"))
        self.label_4.setText(_translate("MainWindow", "图片1"))
        self.rotating_93.setText(_translate("MainWindow", "90°"))
        self.rotating_183.setText(_translate("MainWindow", "180°"))
        self.rotating_274.setText(_translate("MainWindow", "270°"))
        self.rotating_184.setText(_translate("MainWindow", "180°"))
        self.label_5.setText(_translate("MainWindow", "图片1"))
        self.rotating_94.setText(_translate("MainWindow", "90°"))
        self.rotating_275.setText(_translate("MainWindow", "270°"))
        self.rotating_95.setText(_translate("MainWindow", "90°"))
        self.label_6.setText(_translate("MainWindow", "图片1"))
        self.rotating_185.setText(_translate("MainWindow", "180°"))
        self.rotating_186.setText(_translate("MainWindow", "180°"))
        self.rotating_276.setText(_translate("MainWindow", "270°"))
        self.rotating_187.setText(_translate("MainWindow", "180°"))
        self.rotating_188.setText(_translate("MainWindow", "180°"))
        self.rotating_277.setText(_translate("MainWindow", "270°"))
        self.rotating_96.setText(_translate("MainWindow", "90°"))
        self.rotating_278.setText(_translate("MainWindow", "270°"))
        self.rotating_97.setText(_translate("MainWindow", "90°"))
        self.rotating_98.setText(_translate("MainWindow", "90°"))
        self.label_9.setText(_translate("MainWindow", "图片1"))
        self.rotating_189.setText(_translate("MainWindow", "180°"))
        self.label_11.setText(_translate("MainWindow", "图片1"))
        self.rotating_99.setText(_translate("MainWindow", "90°"))
        self.rotating_279.setText(_translate("MainWindow", "270°"))
        self.label_7.setText(_translate("MainWindow", "图片1"))
        self.rotating_190.setText(_translate("MainWindow", "180°"))
        self.rotating_100.setText(_translate("MainWindow", "90°"))
        self.label_10.setText(_translate("MainWindow", "图片1"))
        self.label_12.setText(_translate("MainWindow", "图片1"))
        self.rotating_280.setText(_translate("MainWindow", "270°"))
        self.rotating_281.setText(_translate("MainWindow", "270°"))
        self.rotating_191.setText(_translate("MainWindow", "180°"))
        self.rotating_101.setText(_translate("MainWindow", "90°"))
        self.label_8.setText(_translate("MainWindow", "图片1"))
        self.label_14.setText(_translate("MainWindow", "图片1"))
        self.rotating_282.setText(_translate("MainWindow", "270°"))
        self.label_15.setText(_translate("MainWindow", "图片1"))
        self.rotating_192.setText(_translate("MainWindow", "180°"))
        self.rotating_102.setText(_translate("MainWindow", "90°"))
        self.label_18.setText(_translate("MainWindow", "图片1"))
        self.label_13.setText(_translate("MainWindow", "图片1"))
        self.label_17.setText(_translate("MainWindow", "图片1"))
        self.rotating_193.setText(_translate("MainWindow", "180°"))
        self.rotating_103.setText(_translate("MainWindow", "90°"))
        self.rotating_283.setText(_translate("MainWindow", "270°"))
        self.rotating_104.setText(_translate("MainWindow", "90°"))
        self.rotating_105.setText(_translate("MainWindow", "90°"))
        self.rotating_106.setText(_translate("MainWindow", "90°"))
        self.rotating_284.setText(_translate("MainWindow", "270°"))
        self.rotating_194.setText(_translate("MainWindow", "180°"))
        self.rotating_195.setText(_translate("MainWindow", "180°"))
        self.rotating_196.setText(_translate("MainWindow", "180°"))
        self.rotating_285.setText(_translate("MainWindow", "270°"))
        self.rotating_286.setText(_translate("MainWindow", "270°"))
        self.rotating_107.setText(_translate("MainWindow", "90°"))
        self.rotating_197.setText(_translate("MainWindow", "180°"))
        self.label_16.setText(_translate("MainWindow", "图片1"))
        self.rotating_287.setText(_translate("MainWindow", "270°"))
